repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.2
    hooks:
      - id: prettier
        entry: prettier --write --single-quote --trailing-comma=all
        files: "\\.(\
          css|less|scss\
          |graphql|gql\
          |js|jsx\
          |json\
          |md|markdown|mdown|mkdn\
          |mdx\
          |ts|tsx\
          |yaml|yml\
          )$"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/hadialqattan/pycln
    rev: v0.0.1-beta.0 # Possible releases: https://github.com/hadialqattan/pycln/tags
    hooks:
      - id: pycln
  - repo: https://github.com/PyCQA/isort
    rev: '5.6.4'
    hooks:
      - id: isort
        args: ['--profile', 'black']
